import org.gradle.internal.os.OperatingSystem

plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.4.0' apply false
}

subprojects {
    apply plugin: 'java-library'
    version = mod_version
    group = mod_group_id
    java.toolchain.languageVersion = JavaLanguageVersion.of(25)
}

tasks.register('buildNativeWindows', Exec) {
    onlyIf { OperatingSystem.current().windows }
    workingDir projectDir
    commandLine 'cmd.exe', '/d', '/c', 'native\\build-native.bat'
}

tasks.register('buildNativeMacos', Exec) {
    onlyIf { OperatingSystem.current().macOsX }
    workingDir projectDir
    commandLine 'bash', 'native/build-native-macos.sh'
}

tasks.register('buildNative') {
    dependsOn tasks.named('buildNativeWindows'), tasks.named('buildNativeMacos')
}
