org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.code.style=official
kotlin.stdlib.default.dependency=false
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.77
fabric_loom_version=1.18.2
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.2
fabric_language_kotlin_version=1.14.1+kotlin.2.4.20
mod_id=singularity
mod_name=Singularity
mod_license=MPL-2.0
mod_version=0.1.0-dev
mod_group_id=dev.viincnt.singularity
