modLoader="kotlinforforge"
loaderVersion="[6.3,7)"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''Experimental DLSS integration for Mojang's Vulkan renderer. Research prototype; upscaling is not implemented yet.'''
[[mixins]]
config="singularity.mixins.json"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
